---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: Instalamos Apache
    package:
      name: httpd
      state: latest
    tags: instalar
  - name: Iniciamos el servicio y configuramos el arranque
    service:
      name: httpd
      state: started
      enabled: yes
    tags: instalar
  - name: creamos la pagina de inicio
    file:
      path: /var/www/html/index.html
      state: touch
    tags: configuracion
  - name: añadimos contenido al fichero
    copy:
      content: "Prueba de playbook"
      dest: /var/www/html/index.html
    tags: configuracion
    name: Desinstalar Apache
      service:
        name: httpd
        state: absent
      tags: desinstalar

